name: Allure Report Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Copy Allure data from previous runs
        run: cp -r allure-results allure-results-previous || true

      - name: Create Allure report
        run: |
          allure generate allure-results --clean -o allure-report
          allure open allure-report

      - name: Checkout gh-pages branch
        run: git checkout -B gh-pages

      - name: Copy Allure report to gh-pages branch
        run: cp -r allure-report/* .

      - name: Commit and push Allure report to gh-pages branch
        run: |
          git config --global user.email "styrkink@gmail.com"
          git config --global user.name "styrkink"
          git add .
          git commit -m "Update Allure report"
          git push -f origin gh-pages

      - name: Setup GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

      - name: Update repository description with GitHub Pages link
        run: |
          REPO_URL="https://${{ github.repository_owner }}.github.io/${{ github.repository }}/"
          DESCRIPTION="Allure report available at: $REPO_URL"
          gh api -X PATCH /repos/${{ github.repository }} -f description="$DESCRIPTION"
